/*
# Migration 4: Career Explorer & Roadmaps

## Summary
Creates the career paths catalog (40+ careers) and personalized roadmaps
generated by SIDDHI AI. Each career has a category, salary range, growth
projection, required skills, and steps. Users can save careers they're
interested in and generate personalized roadmaps.

## New Tables

### careers
- id (uuid, PK)
- title (text)
- category (text)
- emoji (text)
- description (text)
- salary_min, salary_max (numeric, LPA)
- growth (text: Very High / High / Moderate / Stable)
- skills (text[])
- roadmap_steps (text[])
- created_at

### saved_careers
- id (uuid, PK)
- user_id (uuid, FK → profiles.id)
- career_id (uuid, FK → careers.id)
- created_at
- UNIQUE (user_id, career_id)

### roadmaps
- id (uuid, PK)
- user_id (uuid, FK → profiles.id)
- career_id (uuid, FK → careers.id, nullable)
- title (text)
- steps (jsonb — array of {step, description, completed})
- progress (int, 0–100)
- created_at, updated_at

## Security
- Careers: public read for all authenticated users; only admins can write.
- Saved careers: users own their saves.
- Roadmaps: users own their roadmaps.
*/

-- ─── CAREERS ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS careers (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title         text NOT NULL,
  category      text,
  emoji         text,
  description   text,
  salary_min    numeric,
  salary_max    numeric,
  growth        text,
  skills        text[] DEFAULT '{}',
  roadmap_steps text[] DEFAULT '{}',
  created_at    timestamptz DEFAULT now()
);

ALTER TABLE careers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "careers_select_all" ON careers;
CREATE POLICY "careers_select_all" ON careers FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "careers_insert_admin" ON careers;
CREATE POLICY "careers_insert_admin" ON careers FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "careers_update_admin" ON careers;
CREATE POLICY "careers_update_admin" ON careers FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "careers_delete_admin" ON careers;
CREATE POLICY "careers_delete_admin" ON careers FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

CREATE INDEX IF NOT EXISTS idx_careers_category ON careers(category);

-- ─── SAVED CAREERS ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_careers (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  career_id   uuid NOT NULL REFERENCES careers(id) ON DELETE CASCADE,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (user_id, career_id)
);

ALTER TABLE saved_careers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "saved_careers_select_own" ON saved_careers;
CREATE POLICY "saved_careers_select_own" ON saved_careers FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "saved_careers_insert_own" ON saved_careers;
CREATE POLICY "saved_careers_insert_own" ON saved_careers FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "saved_careers_delete_own" ON saved_careers;
CREATE POLICY "saved_careers_delete_own" ON saved_careers FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_saved_careers_user ON saved_careers(user_id);

-- ─── ROADMAPS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roadmaps (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  career_id   uuid REFERENCES careers(id) ON DELETE SET NULL,
  title       text NOT NULL,
  steps       jsonb NOT NULL DEFAULT '[]',
  progress    int NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

ALTER TABLE roadmaps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "roadmaps_select_own" ON roadmaps;
CREATE POLICY "roadmaps_select_own" ON roadmaps FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "roadmaps_insert_own" ON roadmaps;
CREATE POLICY "roadmaps_insert_own" ON roadmaps FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "roadmaps_update_own" ON roadmaps;
CREATE POLICY "roadmaps_update_own" ON roadmaps FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "roadmaps_delete_own" ON roadmaps;
CREATE POLICY "roadmaps_delete_own" ON roadmaps FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_roadmaps_user ON roadmaps(user_id);

DROP TRIGGER IF EXISTS roadmaps_updated_at ON roadmaps;
CREATE TRIGGER roadmaps_updated_at BEFORE UPDATE ON roadmaps
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
